from _typeshed import Incomplete
from octoprint.settings import settings as settings
from octoprint.util import dict_contains_keys as dict_contains_keys, dict_merge as dict_merge, dict_sanitize as dict_sanitize, is_hidden_path as is_hidden_path, yaml as yaml

class SaveError(Exception): ...
class CouldNotOverwriteError(SaveError): ...
class InvalidProfileError(Exception): ...

class BedFormFactor:
    RECTANGULAR: str
    CIRCULAR: str
    @classmethod
    def values(cls): ...
BedTypes = BedFormFactor

class BedOrigin:
    LOWERLEFT: str
    CENTER: str
    @classmethod
    def values(cls): ...

class PrinterProfileManager:
    default: Incomplete
    def __init__(self) -> None: ...
    def select(self, identifier): ...
    def deselect(self) -> None: ...
    def get_all(self): ...
    def get(self, identifier): ...
    def remove(self, identifier, trigger_event: bool = False): ...
    def save(self, profile, allow_overwrite: bool = False, make_default: bool = False, trigger_event: bool = False): ...
    def is_default_unmodified(self): ...
    @property
    def profile_count(self): ...
    @property
    def last_modified(self): ...
    def get_default(self): ...
    def set_default(self, identifier) -> None: ...
    def get_current_or_default(self): ...
    def get_current(self): ...
    def exists(self, identifier): ...
