import types
from typing import Any

abiflags: str
api_version: int
argv: list
base_exec_prefix: str
base_prefix: str
builtin_module_names: tuple
byteorder: str
copyright: str
dont_write_bytecode: bool
exec_prefix: str
executable: str
flags: flags
float_info: float_info
float_repr_style: str
hash_info: hash_info
hexversion: int
implementation: types.SimpleNamespace
int_info: int_info
maxsize: int
maxunicode: int
meta_path: list
modules: dict
orig_argv: list
path: list
path_hooks: list
path_importer_cache: dict
platform: str
platlibdir: str
prefix: str
pycache_prefix: None
stdlib_module_names: frozenset
thread_info: thread_info
version: str
version_info: version_info
warnoptions: list

def __breakpointhook__(*args, **kwargs): ...
def __displayhook__(*args, **kwargs): ...
def __excepthook__(*args, **kwargs): ...
def __unraisablehook__(*args, **kwargs): ...
def activate_stack_trampoline(*args, **kwargs): ...
def addaudithook(*args, **kwargs): ...
def audit(event, *args) -> Any: ...
def breakpointhook(*args, **kws) -> Any: ...
def call_tracing(*args, **kwargs): ...
def deactivate_stack_trampoline(*args, **kwargs): ...
def displayhook(*args, **kwargs): ...
def exc_info(*args, **kwargs): ...
def excepthook(*args, **kwargs): ...
def exception(*args, **kwargs): ...
def exit(*args, **kwargs): ...
def get_asyncgen_hooks(*args, **kwargs): ...
def get_coroutine_origin_tracking_depth(*args, **kwargs): ...
def get_int_max_str_digits(*args, **kwargs): ...
def getallocatedblocks(*args, **kwargs): ...
def getdefaultencoding(*args, **kwargs): ...
def getdlopenflags(*args, **kwargs): ...
def getfilesystemencodeerrors(*args, **kwargs): ...
def getfilesystemencoding(*args, **kwargs): ...
def getprofile(*args, **kwargs): ...
def getrecursionlimit(*args, **kwargs): ...
def getrefcount() -> Any: ...
def getsizeof(*args, **kwargs): ...
def getswitchinterval(*args, **kwargs): ...
def gettrace(*args, **kwargs): ...
def getunicodeinternedsize(*args, **kwargs): ...
def intern(*args, **kwargs): ...
def is_finalizing(*args, **kwargs): ...
def is_stack_trampoline_active(*args, **kwargs): ...
def set_asyncgen_hooks(*args, **kwargs): ...
def set_coroutine_origin_tracking_depth(*args, **kwargs): ...
def set_int_max_str_digits(*args, **kwargs): ...
def setdlopenflags(*args, **kwargs): ...
def setprofile(function) -> Any: ...
def setrecursionlimit(*args, **kwargs): ...
def setswitchinterval(*args, **kwargs): ...
def settrace(function) -> Any: ...
def unraisablehook(*args, **kwargs): ...
